# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: kellylynnerowland@gmail.com
author_name: Kelly L. Rowland
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: jupytercon2025-extension-workshop
project_short_description: A JupyterLab extension that displays a random image and
    caption.
python_name: jupytercon2025_extension_workshop
repository: https://github.com/kellyrowland/jupytercon2025-extension-workshop
test: true

